# Site settings Update for my Blog : spaceg.github.io Do.9.April 15.49:24 2015 
title: Jimmy Jin
email: nmbqz@hotmail.com
description: "Hello, My Name is Jimmy Jin, I'm a Gopher and Android Developer from China. This is my Personal Notice and Archive Work Experience Work Blog."
baseurl: ""
url: "http://JimmyJin.me"
twitter_username: JimmyJin
github_username:  jy03189211
instagram_username:  jimmyfliesmacross


# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

paginate: 5 #posts per page

